INSERT INTO role (id, role) VALUES (1, 'CLIENT');
INSERT INTO role (id, role) VALUES (2, 'SELLER');
INSERT INTO role (id, role) VALUES (3, 'COURIER');

INSERT INTO flower (id, name, price, imagelink, hover_image_link, imagelink2, imagelink3, imagelink4, explanation) VALUES (1, 'Bonsai Tree', '$180', 'img/bg-img/bonsai2.jpg', 'img/product-img/product3.jpg', 'img/product-img/product3.jpg', 'img/product-img/product3.jpg', 'img/product-img/product3.jpg', 'In the most restrictive sense, "bonsai" refers to miniaturized, container-grown trees adhering to Japanese tradition and principles. ...');
INSERT INTO flower (id, name, price, imagelink, hover_image_link, imagelink2, imagelink3, imagelink4, explanation) VALUES (2, 'Aloe Vera w/ Square Pot', '$100', 'img/bg-img/2.jpg', 'img/product-img/product4.jpg', 'img/product-img/product4.jpg', 'img/product-img/product4.jpg', 'img/product-img/product4.jpg', 'Aloe vera is a stemless or very short-stemmed plant growing to 60–100 cm (24–39 in) tall, spreading by offsets. The leaves are thick and fleshy, green to grey-green, with some varieties showing white flecks on their upper and lower stem surfaces. The margin of the leaf is serrated and has small white teeth.');
INSERT INTO flower (id, name, price, imagelink, hover_image_link, imagelink2, imagelink3, imagelink4, explanation) VALUES (3, 'Box Flower', '$150', 'img/bg-img/box_flower.jpeg', 'img/product-img/product5.jpg', 'img/product-img/product5.jpg', 'img/product-img/product5.jpg', 'img/product-img/product5.jpg', 'A flower box is a type of container in the form of a planter or box that is usually placed outdoors and used for displaying live plants and flowers, but it may also be used for growing herbs or other edible plants.');
INSERT INTO flower (id, name, price, imagelink, hover_image_link, imagelink2, imagelink3, imagelink4, explanation) VALUES (4, 'Cactus', '$80', 'img/bg-img/4.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'Almost all cacti are succulents, meaning they have thickened, fleshy parts adapted to store water. Unlike many other succulents, the stem is the only part of most cacti where this vital process takes place. Most species of cacti have lost true leaves, retaining only spines, which are highly modified leaves.');
INSERT INTO flower (id, name, price, imagelink, hover_image_link, imagelink2, imagelink3, imagelink4, explanation) VALUES (5, 'Plant Pot', '$18', 'img/bg-img/5.jpg', 'img/product-img/product1.jpg', 'img/product-img/product1.jpg', 'img/product-img/product1.jpg', 'img/product-img/product1.jpg', 'A flowerpot, flower pot, planter, or plant pot is a container in which flowers and other plants are cultivated and displayed.');
INSERT INTO flower (id, name, price, imagelink, hover_image_link, imagelink2, imagelink3, imagelink4, explanation) VALUES (6, 'Bouquet of Flowers', '$110', 'img/bg-img/buket_çiçek.jpeg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'A flower bouquet is a collection of flowers in a creative arrangement. Flower bouquets can be arranged for the decor of homes or public buildings, or may be handheld. Handheld bouquets are classified by several different popular shapes and styles, including nosegay, crescent, and cascading bouquets.');
INSERT INTO flower (id, name, price, imagelink, hover_image_link, imagelink2, imagelink3, imagelink4, explanation) VALUES (7, 'Large Gift Box', '$500', 'img/bg-img/large_gift_box.jpeg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'One price, hundreds of experiences: One gift buys you an entire collection of amazing experiences for the recipient to choose from. The recipient can then choose the ONE experience they want, and book it with just a couple of clicks. Simple!');
INSERT INTO flower (id, name, price, imagelink, hover_image_link, imagelink2, imagelink3, imagelink4, explanation) VALUES (8, 'Small Gift Box', '$300', 'img/bg-img/small_gift_box.jpeg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'One price, hundreds of experiences: One gift buys you an entire collection of amazing experiences for the recipient to choose from. The recipient can then choose the ONE experience they want, and book it with just a couple of clicks. Simple!');
INSERT INTO flower (id, name, price, imagelink, hover_image_link, imagelink2, imagelink3, imagelink4, explanation) VALUES (9, 'Home Deco', '$50', 'img/bg-img/9.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'img/product-img/product6.jpg', 'Natural plants bring unsurpassed charm inside a dwelling, thanks to their diverse leaf shapes, colors, textures and growing styles. Be it modern or more on the country style, your house will look more lively and sophisticated with some thoughtfully-placed flower pots that highlight certain indoor areas. And growing them does not have to become a chore; by choosing some low-maintenance species that also look enticing, you will add effortless panache to your interior design.');
INSERT INTO flower (id, name, price, imagelink, hover_image_link, imagelink2, imagelink3, imagelink4, explanation) VALUES (10, 'Red Rose', '$15', 'img/core-img/red-rose.jpg', 'img/product-img/product2.jpg', 'img/product-img/product2.jpg', 'img/product-img/product2.jpg', 'img/product-img/product2.jpg', 'The poem opens with one of the most famous similes of all time. The speaker is saying his love is like a really red rose that is "newly sprung in June." In other words, the speaker''s love is like a flower that has just emerged from the ground. You know what that means, Shmoopers: his love is new, fresh, and young.');